# Generated by Django 5.1.6 on 2025-02-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadedfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default='NA', max_length=20, unique=True),
        ),
    ]
