# Generated by Django 5.1.5 on 2025-02-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_uploadedfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
