# Generated by Django 5.1.5 on 2025-02-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_uploadedfile_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default='NA', max_length=40, unique=True),
        ),
    ]
